fix: publication year is optional
platform-coop-toolkit/coop-library-framework pull request #293
Opened 2020-02-24 16:10 UTC by greatislander

* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Pass dates to hidden publication date field on change of year, month, or day fields.

## Steps to test

1. 
2. 
3. 

**Expected behavior:** 

## Additional information

## Related issues

2020-02-24 21:06 UTC, jhung requested changes
I found a bug but not sure if it's related to the changes in this PR.

If you omit a publication year, but specify a month and day, upon saving the resource the publication day reverts to "none".

2020-02-25 18:12 UTC, jhung requested changes
The publication day number field only has "None" as an option if resource is submitted with a Month but no date.

**To reproduce**
1. Add a new resource
2. Specify March as month published
3. Submit the resource
4. Notice the Publication Day selector just as "None" as an option.

Expected behaviour:
*  if no Publication Day is specified, but a month is specified, then the date value should be "None" with other numeric days selectable for that month.
* if no Publication Day is specified, but only a year is specified and no month, then the Publication Day should have "None" as the only option.

2020-02-25 18:23 UTC, greatislander commented
@jhung I can't reproduce this. Can you run `npm run build` and re-test?

2020-02-25 19:34 UTC, jhung approved these changes

2020-02-25 19:35 UTC, merged