feat: add term order field (resolves #294)
platform-coop-toolkit/coop-library-framework pull request #295
Opened 2020-02-24 19:02 UTC by greatislander

* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Adds a custom meta field to topics and goals which allows a numeric order to be assigned.

## Steps to test

1. Edit a topic or goal.

**Expected behavior:** Order can be customized.

## Additional information

Front-end implementation will be completed in https://github.com/platform-coop-toolkit/coop-library/issues/168.

## Related issues

- Resolves #294.

2020-02-24 20:30 UTC, jhung requested changes
May need to add some input validation for the field. I can enter a random string and it would preserve that.

2020-02-24 21:13 UTC, greatislander commented
@jhung Found a plugin that does this better, and bypasses the issue with `meta_value`.

2020-02-25 14:35 UTC, jhung requested changes
In the Topics list, the order input field is a spinner that can be negative values. Negative values should either not be allowed or corrected to 0.

Also the number spinner is inconsistent with the field that appears when viewing a single topic. Should probably use the same input method in all cases.

As seen in Topic list:
![image](https://user-images.githubusercontent.com/564762/75256349-57aced00-57b1-11ea-8dc3-e43880b3a7ab.png)

As seen in single Topic:
![image](https://user-images.githubusercontent.com/564762/75256513-8dea6c80-57b1-11ea-9bea-ffad8926636d.png)

2020-02-25 14:57 UTC, greatislander commented
@jhung I'd have to patch the plugin to change this — do you consider it a dealbreaker?

2020-02-25 17:52 UTC, jhung commented
> @jhung I'd have to patch the third-party plugin to change this — do you consider it a dealbreaker?

@greatislander Not a dealbreaker if it can't be done easily. 

Can the negative values be sanitized however?

2020-02-25 18:57 UTC, greatislander commented
@jhung I decided it was best to fork so as to implement these changes. You'll need to trash the `wp-term-order` plugin from your plugins directory, then [our fork](https://github.com/platform-coop-toolkit/wp-term-order/) will be installed.

2020-02-25 20:31 UTC, jhung commented
> @jhung I decided it was best to fork so as to implement these changes. You'll need to trash the `wp-term-order` plugin from your plugins directory, then [our fork](https://github.com/platform-coop-toolkit/wp-term-order/) will be installed.

This would require maintaining this fork just to avoid negative numbers on the input? Not sure if the increased technical burden is justified. Do we gain anything else by using our fork?

2020-02-25 20:33 UTC, greatislander commented
@jhung I think it’s worth it, as the plugin doesn’t appear to be accepting pull requests and I already had to use a filter to fix a different issue. It uses stable APIs and I think there’s very minimal need for maintenance.

2020-02-25 21:30 UTC, jhung approved these changes

2020-02-25 21:35 UTC, merged